.PHONY: begin install-deps check-health init-git help

help:
	@echo "LORE — Learning Operational Resource Engine"
	@echo ""
	@echo "Commands:"
	@echo "  make begin       Run interactive setup (recommended for new users)"
	@echo "  make install-deps Install Python dependencies for sync scripts"
	@echo "  make check-health Verify sources and jobs are configured"
	@echo "  make init-git     Initialize git repo and make first commit"
	@echo "  make schedule     Schedule sync jobs with launchd (macOS)"

begin:
	@echo "=== LORE Setup ==="
	@echo ""
	@echo "Step 1: Fill in your identity and communication style"
	@echo "  Open: ~ Reference/identity.md"
	@echo "  Open: ~ Reference/comms.md"
	@echo ""
	@echo "Step 2: Open this folder as an Obsidian vault"
	@echo "  Obsidian → Open folder as vault → $(PWD)"
	@echo ""
	@echo "Step 3: Answer your setup questions"
	@echo "  Open: ! Start Here/setup-questions.md"
	@echo "  Answer all questions, save the file"
	@echo ""
	@echo "Step 4: Open Claude Code in this folder"
	@echo "  cd $(PWD) && claude"
	@echo ""
	@echo "Step 5: Record your origin"
	@echo "  In Claude Code, type: /begin"
	@echo "  Wait 2-4 minutes while LORE writes your Reference files"
	@echo ""
	@echo "Step 6: Connect your first source"
	@echo "  Drop a meeting transcript or notes file into Raw/"
	@echo "  In Claude Code, type: /ingest"
	@echo "  Or: 'connect granola' for automatic meeting sync (Mac only)"
	@echo ""
	@echo "Step 7: Close your first chapter after one week"
	@echo "  In Claude Code, type: /chapter"
	@echo ""
	@echo "Done. See README.md for the full First Week plan."

install-deps:
	pip install requests python-frontmatter python-dateutil

check-health:
	@echo "Checking LORE structure..."
	@test -f CLAUDE.md && echo "  CLAUDE.md: ok" || echo "  CLAUDE.md: MISSING"
	@test -f "~ Reference/identity.md" && echo "  identity.md: ok" || echo "  identity.md: MISSING"
	@test -f "~ Reference/comms.md" && echo "  comms.md: ok" || echo "  comms.md: MISSING"
	@test -f "Wiki/index.md" && echo "  Wiki/index.md: ok" || echo "  Wiki/index.md: MISSING"
	@test -d .claude/skills && echo "  Skills: ok" || echo "  Skills: MISSING"
	@echo "Done."

init-git:
	git init
	git add CLAUDE.md README.md Makefile
	git add "! Start Here/"
	git add ".claude/skills/"
	git add ".claude/settings.json"
	git add "Wiki/index.md"
	git add "Wiki/hot.md"
	git add "Wiki/log.md"
	git add "Wiki/~System/templates/"
	git add "~ Reference/"
	git commit -m "Initial LORE scaffold"
	@echo ""
	@echo "Repo initialized. Push to GitHub:"
	@echo "  gh repo create LORE --public --source=. --push"

schedule:
	@echo "=== LORE Schedule ==="
	@echo ""
	@echo "Granola sync: handled automatically by the Obsidian Granola Sync plugin."
	@echo "  Configure in Obsidian → Settings → Granola Sync → Sync interval: 900"
	@echo "  No launchd job needed."
	@echo ""
	@echo "Gmail / Slack sync: scripts are built by Claude on demand."
	@echo "  Step 1: Open Claude Code and type: implement gmail sync"
	@echo "  Step 2: Once the script exists at Wiki/~System/sync/, run:"
	@echo "    make schedule-gmail"
	@echo ""
	@echo "See ! Start Here/CONNECTIONS.md → Advanced: Automation for the Shell Commands"
	@echo "plugin, which auto-triggers Claude workflows on vault events."
